version: "3.8"

services:

  postgres:
    image: postgres:14
    container_name: mayan_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mayan
      POSTGRES_USER: mayan
      POSTGRES_PASSWORD: mayan123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - mayan_postgres_data_hospital:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mayan"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mayan_net_hospital

  redis:
    image: redis:7
    container_name: mayan_redis
    restart: unless-stopped
    volumes:
      - mayan_redis_data_hospital:/data
    networks:
      - mayan_net_hospital

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: mayan_elasticsearch_hospital
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
    volumes:
      - mayan_elastic_data_hospital:/usr/share/elasticsearch/data
    networks:
      - mayan_net_hospital

  mayan:   
    image: mayanedms/mayanedms:latest
    container_name: mayan_edms
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - libreoffice
    environment:
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: postgres
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_PASSWORD: mayan123

      MAYAN_REDIS_URL: redis://redis:6379/0
      MAYAN_CELERY_BROKER_URL: redis://redis:6379/0
      MAYAN_ELASTICSEARCH_HOSTS: elasticsearch:9200
   

      # 🔹 LANGUE & LOCALISATION
      MAYAN_LANGUAGE_CODE: fr
      MAYAN_TIME_ZONE: Africa/Abidjan

      # 🔹 OCR FRANÇAIS
      MAYAN_OCR_BACKEND: mayan.apps.ocr.backends.tesseract.TesseractBackend
      MAYAN_OCR_LANGUAGE: fra
      #
      MAYAN_DOCUMENT_FILE_PAGE_PROCESSORS: >
        mayan.apps.converter.layers.ConvertLayer
      MAYAN_CONVERTER_BACKEND: mayan.apps.converter.backends.libreoffice.OfficeBackend
      MAYAN_CONVERTER_LIBREOFFICE_CONNECTION: socket,host=libreoffice,port=2002;urp;
      MAYAN_ALLOWED_HOSTS: "*"
    ports:
      - "8050:8000"
    volumes:
      - mayan_media_hospital:/var/lib/mayan
    networks:
      - mayan_net_hospital
  
  mayan_worker:
    image: mayanedms/mayanedms:latest
    container_name: mayan_worker
    restart: unless-stopped
    command: celery -A mayan worker -l INFO
    depends_on:
      - mayan
      - libreoffice
    volumes:
      - mayan_media_hospital:/var/lib/mayan
    networks:
      - mayan_net_hospital

  mayan_beat:
    image: mayanedms/mayanedms:latest
    container_name: mayan_beat
    restart: unless-stopped
    command: celery -A mayan beat -l INFO
    depends_on:
      - mayan
    volumes:
      - mayan_media_hospital:/var/lib/mayan
    networks:
      - mayan_net_hospital 
      
  libreoffice:
    image: ghcr.io/linuxserver/libreoffice
    container_name: mayan_libreoffice
    restart: unless-stopped 
    command: > 
      soffice --headless --accept="socket,host=0.0.0.0,port=2002;urp;" --nofirststartwizard
    ports:
    - "2002:2002"
    networks: 
    - mayan_net_hospital
    
networks:
  mayan_net_hospital:
    driver: bridge

volumes:
  mayan_postgres_data_hospital:
  mayan_elastic_data_hospital:
  mayan_media_hospital:
  mayan_redis_data_hospital:

